In [1]:
import numpy as np

## Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
a=np.nan*np.empty(10)
a[4]=1

In [27]:
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

## Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [30]:
# a,b = map(int, input("Enter two numbers: ").split())

a=int(input("enter number"))
b=int(input("enter number"))
x=np.random.random((a,b))
print(x)
print(np.mean(x))

enter number 1
enter number 11


[[0.3360469  0.81701187 0.54740845 0.15799269 0.51876706 0.53594645
  0.93225085 0.19095893 0.89871132 0.86317276 0.70014521]]
0.590764770757858


##  Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [33]:
def borderarray(a,b):
    x=np.ones((a,b))
    x[1:-1,1:-1]=0
    return x
borderarray(4,5)    

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [40]:
a1=np.linspace(0,1,12)[1:-1]
a1

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [42]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##  Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [43]:
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

##  Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [48]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)


array([100,  37,   1,  83, 113,  44,  60,  54, 105,  63])

## Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [50]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### Q-9: Arrays
You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

In [ ]:
a=input().strip().split
np.array(a[::-1], dtype=np.float32)